GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFzc2VyIiwiaWF0IjoxNjMxMjI1NTUzLCJleHAiOjE2MzEyMjU2NzN9.7DMzPOYsKsE7JcDBFPjRil90vB39DyBunRej14laCVI

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFzc2VyIiwiaWF0IjoxNjMxMjI1NTUzfQ.OcUqjXvX1mPZ1tvPhQev16db1P02-p-cNdECBHdg7Ao"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFzc2VyIiwiaWF0IjoxNjMxMjI1NTUzfQ.OcUqjXvX1mPZ1tvPhQev16db1P02-p-cNdECBHdg7Ao"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Nasser"
}